name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  repository_dispatch:
    types: [test_result]
    
env:
    ENV_FILE: ${{ secrets.ENV_FILE }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
    - uses: actions/checkout@v3
    - name: Build the stack
      run: |
        echo $ENV_FILE  > .env
        docker-compose  --env-file .env  -f ./lira_backend_api/deploy/docker-compose.yml  --project-directory ../ up --build
