name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  repository_dispatch:
    types: [test_result]
jobs:
  build:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
          node-version: 16
    - run: npm install
    - uses: ./
      with:
         compose-file: "./lira_backend_api/deploy/docker-compose.yml"        
         services: api
         up-flags: "--build"
         compose-flags: "--project-directory"
